// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/header-variants/BoldGradient.tsx": () => import("../components/mockups/header-variants/BoldGradient.tsx"),
  "./components/mockups/header-variants/DarkPremium.tsx": () => import("../components/mockups/header-variants/DarkPremium.tsx"),
  "./components/mockups/header-variants/ModernMinimal.tsx": () => import("../components/mockups/header-variants/ModernMinimal.tsx")
};
